server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elderly_health_db
    username: postgres
    password: Admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # use 'create', 'create-drop', or 'validate' as needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false # optional for better LocalDate/Time formatting

# Optional: Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
